# Generated by Django 2.2.2 on 2019-06-23 22:21

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('example', '0001_initial'),
                ('example', '0002_auto_20190623_1501')]

    dependencies = [
    ]

    operations = [
    ]
