# Generated by Django 2.2.2 on 2019-06-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0001_initial'),
    ]

    operations = []
